### ISSUE TITLE
Add to home-assistant

### ISSUE THREAD

**Issue by MariusSchiffer** [markusressel/raspyrfm-hass-component#1]
This component could be submitted to the main home-assistant repo if it is slightly cleaned up.

Do you need help with that?

**Comment by markusressel** [comment]
It's already in progress. Have a look here:
https://github.com/home-assistant/home-assistant/pull/19130

**Comment by MariusSchiffer** [comment]
Oops, sorry, I did not see that.

**Comment by markusressel** [comment]
np :smile:
